# Change these first
owner: edythecow # Your GitHub organization or username, where this repository lives
repo: status.tilt.work # The name of this repository

sites:
  - name: "Tilt.work"
    url: https://tilt.work
  - name: "Backup service"
    check: "tcp-ping"
    url: $BACKUP_SERVER
    port: 80

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tilt.work
  # baseUrl: /your-repo-name
  logoUrl: https://tilt.work/wp-content/uploads/2020/07/cropped-tiltwork_logo_sort-square-900-2-120x120.png
  favicon: https://tilt.work/favicon.ico
  name: Status
  introTitle: ""
  introMessage: 
  navbar:
    #- title: Status
    #  href: / 

i18n:
  footer: " "

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
